# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyword',
            name='last_review',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary_manager.Word'),
        ),
    ]
