# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_auto_20170601_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='translation_to',
            field=models.ManyToManyField(related_name='_language_translation_to_+', to='user_manager.Language'),
        ),
    ]
