# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20170607_1615'),
    ]

    operations = [

    ]
