# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
        ('dictionary_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('additional_information', models.TextField()),
                ('definitions', models.ManyToManyField(to='dictionary_manager.Definition')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='user_manager.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='word',
            name='definitions',
            field=models.ManyToManyField(to='dictionary_manager.Definitions'),
        ),
    ]
