# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_manager', '0003_auto_20170529_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitions',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
